version: '3.8'

services:
  nginx-cors:
    build: .
    container_name: nginx-cors
    ports:
      - "8088:80"
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
